Class {
	#name : 'AASAbstractLangString',
	#superclass : 'AASEntity',
	#traits : 'AASTAbstractLangString',
	#classTraits : 'AASTAbstractLangString classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASAbstractLangString class >> annotation [

	<FMClass: #AbstractLangString super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
