"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `embeddedDataSpecification` | `AASTDataSpecificationContent_choice` | `dataSpecificationContent` | `AASTEmbeddedDataSpecification` | |



"
Class {
	#name : 'AASDataSpecificationContent_choice',
	#superclass : 'AASEntity',
	#traits : 'AASTDataSpecificationContent_choice',
	#classTraits : 'AASTDataSpecificationContent_choice classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASDataSpecificationContent_choice class >> annotation [

	<FMClass: #DataSpecificationContent_choice super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
