"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `annotatedRelationshipElement` | `AASTDataElement_choice` | `annotations` | `AASTAnnotatedRelationshipElement` | |



"
Class {
	#name : 'AASDataElement_choice',
	#superclass : 'AASEntity',
	#traits : 'AASTDataElement_choice',
	#classTraits : 'AASTDataElement_choice classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASDataElement_choice class >> annotation [

	<FMClass: #DataElement_choice super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
