"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `modelType` | `AASTDataSpecificationContent` | `dataSpecificationContent` | `AASTModelType` | |



"
Class {
	#name : 'AASDataSpecificationContent',
	#superclass : 'AASEntity',
	#traits : 'AASTDataSpecificationContent',
	#classTraits : 'AASTDataSpecificationContent classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASDataSpecificationContent class >> annotation [

	<FMClass: #DataSpecificationContent super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
