"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `dataSpecificationIec61360` | `AASTDataTypeIec61360` | `dataType` | `AASTDataSpecificationIec61360` | |


## Properties
======================

| Name | Type | Default value | Comment |
|---|
| `value` | `String` | nil | |

"
Class {
	#name : 'AASDataTypeIec61360',
	#superclass : 'AASEntity',
	#traits : 'AASTDataTypeIec61360',
	#classTraits : 'AASTDataTypeIec61360 classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASDataTypeIec61360 class >> annotation [

	<FMClass: #DataTypeIec61360 super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
