"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `dataSpecificationIec61360` | `AASTLevelType` | `levelType` | `AASTDataSpecificationIec61360` | |



"
Class {
	#name : 'AASLevelType',
	#superclass : 'AASEntity',
	#traits : 'AASTLevelType',
	#classTraits : 'AASTLevelType classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASLevelType class >> annotation [

	<FMClass: #LevelType super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
