"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `dataSpecificationIec61360` | `AASTLangStringPreferredNameTypeIec61360` | `preferredName` | `AASTDataSpecificationIec61360` | |



"
Class {
	#name : 'AASLangStringPreferredNameTypeIec61360',
	#superclass : 'AASEntity',
	#traits : 'AASTAbstractLangString + AASTLangStringPreferredNameTypeIec61360',
	#classTraits : 'AASTAbstractLangString classTrait + AASTLangStringPreferredNameTypeIec61360 classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASLangStringPreferredNameTypeIec61360 class >> annotation [

	<FMClass: #LangStringPreferredNameTypeIec61360 super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
