"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `dataSpecificationIec61360` | `AASTLangStringShortNameTypeIec61360` | `shortName` | `AASTDataSpecificationIec61360` | |



"
Class {
	#name : 'AASLangStringShortNameTypeIec61360',
	#superclass : 'AASEntity',
	#traits : 'AASTAbstractLangString + AASTLangStringShortNameTypeIec61360',
	#classTraits : 'AASTAbstractLangString classTrait + AASTLangStringShortNameTypeIec61360 classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASLangStringShortNameTypeIec61360 class >> annotation [

	<FMClass: #LangStringShortNameTypeIec61360 super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
