"
## Relations
======================

### Other
| Relation | Origin | Opposite | Type | Comment |
|---|
| `dataSpecificationIec61360` | `AASTLangStringDefinitionTypeIec61360` | `definition` | `AASTDataSpecificationIec61360` | |



"
Class {
	#name : 'AASLangStringDefinitionTypeIec61360',
	#superclass : 'AASEntity',
	#traits : 'AASTAbstractLangString + AASTLangStringDefinitionTypeIec61360',
	#classTraits : 'AASTAbstractLangString classTrait + AASTLangStringDefinitionTypeIec61360 classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASLangStringDefinitionTypeIec61360 class >> annotation [

	<FMClass: #LangStringDefinitionTypeIec61360 super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
