Class {
	#name : 'AASRelationshipElement_choice',
	#superclass : 'AASEntity',
	#traits : 'AASTRelationshipElement_choice',
	#classTraits : 'AASTRelationshipElement_choice classTrait',
	#category : 'AASModelEntities-Entities',
	#package : 'AASModelEntities',
	#tag : 'Entities'
}

{ #category : 'meta' }
AASRelationshipElement_choice class >> annotation [

	<FMClass: #RelationshipElement_choice super: #AASEntity>
	<package: #AASModelEntities>
	<generated>
	^ self
]
